name: Invasion
main: "xyz.rodeldev.invasion.Main"
version: 3.0.0
author: rodel77
description: Get a zombie invasion and destroy them with you best swords

commands:
  invasion:
    description: Invasion Command!
  minigameinvasion:
    description: Invasion MiniGame Command!
    alias: [invasionminigame, invasionmg, invasiongame, invasiongames, invasionarena]